"""initial_schema_8_tables

Revision ID: 5f1fd95b5aea
Revises: 
Create Date: 2026-08-24 17:41:23.024197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1fd95b5aea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibility_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dept_a', sa.String(length=20), nullable=False),
    sa.Column('activity_a', sa.String(length=100), nullable=False),
    sa.Column('dept_b', sa.String(length=20), nullable=False),
    sa.Column('activity_b', sa.String(length=100), nullable=False),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_rules_dept_a'), 'compatibility_rules', ['dept_a'], unique=False)
    op.create_index(op.f('ix_compatibility_rules_dept_b'), 'compatibility_rules', ['dept_b'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_department'), 'resources', ['department'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('section_name', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_division'), 'sections', ['division'], unique=False)
    op.create_index(op.f('ix_sections_section_code'), 'sections', ['section_code'], unique=True)
    op.create_index(op.f('ix_sections_zone'), 'sections', ['zone'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_number', sa.String(length=10), nullable=False),
    sa.Column('train_name', sa.String(length=200), nullable=False),
    sa.Column('train_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_index(op.f('ix_trains_train_type'), 'trains', ['train_type'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_code', sa.String(length=20), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('train_impact_count', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('optimizer_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_block_code'), 'blocks', ['block_code'], unique=True)
    op.create_index(op.f('ix_blocks_block_date'), 'blocks', ['block_date'], unique=False)
    op.create_index(op.f('ix_blocks_status'), 'blocks', ['status'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_department'), 'maintenance_requests', ['department'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_priority'), 'maintenance_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_request_code'), 'maintenance_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_maintenance_requests_status'), 'maintenance_requests', ['status'], unique=False)
    op.create_table('train_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_movements_day_of_week'), 'train_movements', ['day_of_week'], unique=False)
    op.create_table('block_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_request_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_jobs')
    op.drop_index(op.f('ix_train_movements_day_of_week'), table_name='train_movements')
    op.drop_table('train_movements')
    op.drop_index(op.f('ix_maintenance_requests_status'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_request_code'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_priority'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_department'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_blocks_status'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_date'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_code'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_trains_train_type'), table_name='trains')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_sections_zone'), table_name='sections')
    op.drop_index(op.f('ix_sections_section_code'), table_name='sections')
    op.drop_index(op.f('ix_sections_division'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_resources_department'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_compatibility_rules_dept_b'), table_name='compatibility_rules')
    op.drop_index(op.f('ix_compatibility_rules_dept_a'), table_name='compatibility_rules')
    op.drop_table('compatibility_rules')
    # ### end Alembic commands ###
